version: "3"

tasks:

  install:
    desc: "Automatically detect and install Python dependencies"
    cmds:
      # generate requirements.txt using pipreqs (overwrite if exists)
      # - pipreqs . --force
      # install all dependencies
      - pip install -r requirements.txt

  run:
    desc: "Run the main script to execute the backtesting pipeline"
    deps: [install]
    cmds:
      - python main.py